fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    gpg_key: git://github.com/treydock/puppet-gpg_key.git
  symlinks:
    repo_centos: "#{source_dir}"
